/*
<a href="http://www.freepik.com">Designed by Titusurya / Freepik</a>
 */
package app2;

import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JColorChooser;

/**
 *
 * @author koren
 */
public class MiColores extends javax.swing.JFrame {

    /**
     * Creates new form MiColores
     */
    private static String cod;
    private static String hex;
    private static String cod1;
    private static String hex1;
    private static String cod2;
    private static String hex2;
    private static String cod6;
    private static String hex6;
    private static String cod3;
    private static String hex3;
    private static String cod4;
    private static String hex4;
    private static String cod5;
    private static String hex5;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMiPaleta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbInsertar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jbConsultar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbVolverMenu = new javax.swing.JButton();
        jpInsertar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jbElegir = new javax.swing.JButton();
        jpRespuesta = new javax.swing.JPanel();
        jlHex = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlRGB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlRGB1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlHex1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jpRespuesta1 = new javax.swing.JPanel();
        jbElegir1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbElegir2 = new javax.swing.JButton();
        jlRGB2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlHex2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jpRespuesta2 = new javax.swing.JPanel();
        INSERTAR = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jbVolverInsertar = new javax.swing.JButton();
        jpActualizar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jbElegir3 = new javax.swing.JButton();
        jpRespuesta3 = new javax.swing.JPanel();
        jlHex3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jlRGB3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jlRGB4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jlHex4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jpRespuesta4 = new javax.swing.JPanel();
        jbElegir4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jbElegir5 = new javax.swing.JButton();
        jlRGB5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jlHex5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jpRespuesta5 = new javax.swing.JPanel();
        ACTUALIZAR = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jbVolverInsertar1 = new javax.swing.JButton();
        jpEliminar = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jbElegir6 = new javax.swing.JButton();
        jpRespuesta6 = new javax.swing.JPanel();
        jlHex6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jlRGB6 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ELIMINAR = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jbVolverInsertar2 = new javax.swing.JButton();
        jpConsultar = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        CONSULTAR = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jbVolverInsertar3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaRESPUESTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));

        jpMiPaleta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel1.setText("MI PALETA DE COLORES PERSONAL");

        jbInsertar.setBackground(new java.awt.Color(153, 255, 153));
        jbInsertar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbInsertar.setText("INSERTAR");
        jbInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInsertarActionPerformed(evt);
            }
        });

        jbActualizar.setBackground(new java.awt.Color(255, 255, 153));
        jbActualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbActualizar.setText("MODIFICAR");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbConsultar.setBackground(new java.awt.Color(153, 204, 255));
        jbConsultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbConsultar.setText("CONSULTAR");
        jbConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarActionPerformed(evt);
            }
        });

        jbEliminar.setBackground(new java.awt.Color(255, 153, 153));
        jbEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbEliminar.setText("ELIMINAR");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app2/Mipaleta1.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app2/Mipaleta2.png"))); // NOI18N

        jbVolverMenu.setBackground(new java.awt.Color(255, 255, 255));
        jbVolverMenu.setText("VOLVER");
        jbVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMiPaletaLayout = new javax.swing.GroupLayout(jpMiPaleta);
        jpMiPaleta.setLayout(jpMiPaletaLayout);
        jpMiPaletaLayout.setHorizontalGroup(
            jpMiPaletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpMiPaletaLayout.createSequentialGroup()
                .addGroup(jpMiPaletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMiPaletaLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpMiPaletaLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jpMiPaletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbVolverMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addComponent(jbActualizar)
                        .addGap(53, 53, 53)
                        .addComponent(jbEliminar)
                        .addGap(51, 51, 51)
                        .addComponent(jbConsultar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMiPaletaLayout.setVerticalGroup(
            jpMiPaletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMiPaletaLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jpMiPaletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInsertar)
                    .addComponent(jbActualizar)
                    .addComponent(jbEliminar)
                    .addComponent(jbConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jbVolverMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        jpInsertar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("HEX");

        jbElegir.setBackground(new java.awt.Color(255, 255, 255));
        jbElegir.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jbElegir.setText("+");
        jbElegir.setBorderPainted(false);
        jbElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbElegirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpRespuestaLayout = new javax.swing.GroupLayout(jpRespuesta);
        jpRespuesta.setLayout(jpRespuestaLayout);
        jpRespuestaLayout.setHorizontalGroup(
            jpRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        jpRespuestaLayout.setVerticalGroup(
            jpRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("RGB");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ELEGIR COLOR PRINCIPAL");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("RGB");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("HEX");

        javax.swing.GroupLayout jpRespuesta1Layout = new javax.swing.GroupLayout(jpRespuesta1);
        jpRespuesta1.setLayout(jpRespuesta1Layout);
        jpRespuesta1Layout.setHorizontalGroup(
            jpRespuesta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        jpRespuesta1Layout.setVerticalGroup(
            jpRespuesta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jbElegir1.setBackground(new java.awt.Color(255, 255, 255));
        jbElegir1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jbElegir1.setText("+");
        jbElegir1.setBorderPainted(false);
        jbElegir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbElegir1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ELEGIR COLORES SECUNDARIOS");

        jLabel5.setText("Se permite solo2 colores secundarios");

        jbElegir2.setBackground(new java.awt.Color(255, 255, 255));
        jbElegir2.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jbElegir2.setText("+");
        jbElegir2.setBorderPainted(false);
        jbElegir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbElegir2ActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("RGB");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("HEX");

        javax.swing.GroupLayout jpRespuesta2Layout = new javax.swing.GroupLayout(jpRespuesta2);
        jpRespuesta2.setLayout(jpRespuesta2Layout);
        jpRespuesta2Layout.setHorizontalGroup(
            jpRespuesta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        jpRespuesta2Layout.setVerticalGroup(
            jpRespuesta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        INSERTAR.setBackground(new java.awt.Color(153, 255, 153));
        INSERTAR.setText("INSERTAR");
        INSERTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSERTARActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app2/Peq1.png"))); // NOI18N

        jbVolverInsertar.setBackground(new java.awt.Color(255, 255, 255));
        jbVolverInsertar.setText("VOLVER");
        jbVolverInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverInsertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpInsertarLayout = new javax.swing.GroupLayout(jpInsertar);
        jpInsertar.setLayout(jpInsertarLayout);
        jpInsertarLayout.setHorizontalGroup(
            jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInsertarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInsertarLayout.createSequentialGroup()
                        .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpInsertarLayout.createSequentialGroup()
                                .addComponent(jpRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlHex, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbElegir)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jlRGB, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                    .addGroup(jpInsertarLayout.createSequentialGroup()
                        .addComponent(jpRespuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlHex1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlRGB1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbElegir1))
                    .addGroup(jpInsertarLayout.createSequentialGroup()
                        .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbVolverInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpRespuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpInsertarLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlHex2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlRGB2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbElegir2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInsertarLayout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(INSERTAR)))))
                .addGap(103, 103, 103))
        );
        jpInsertarLayout.setVerticalGroup(
            jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInsertarLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlRGB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlHex, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpRespuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlHex1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpInsertarLayout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlRGB1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jbElegir1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpRespuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlHex2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpInsertarLayout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlRGB2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jbElegir2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89)
                .addGroup(jpInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INSERTAR)
                    .addComponent(jbVolverInsertar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel13))
        );

        jpActualizar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("HEX");

        jbElegir3.setBackground(new java.awt.Color(255, 255, 255));
        jbElegir3.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jbElegir3.setText("+");
        jbElegir3.setBorderPainted(false);
        jbElegir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbElegir3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpRespuesta3Layout = new javax.swing.GroupLayout(jpRespuesta3);
        jpRespuesta3.setLayout(jpRespuesta3Layout);
        jpRespuesta3Layout.setHorizontalGroup(
            jpRespuesta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        jpRespuesta3Layout.setVerticalGroup(
            jpRespuesta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("RGB");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("ELEGIR COLOR PRINCIPAL");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("RGB");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("HEX");

        javax.swing.GroupLayout jpRespuesta4Layout = new javax.swing.GroupLayout(jpRespuesta4);
        jpRespuesta4.setLayout(jpRespuesta4Layout);
        jpRespuesta4Layout.setHorizontalGroup(
            jpRespuesta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        jpRespuesta4Layout.setVerticalGroup(
            jpRespuesta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jbElegir4.setBackground(new java.awt.Color(255, 255, 255));
        jbElegir4.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jbElegir4.setText("+");
        jbElegir4.setBorderPainted(false);
        jbElegir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbElegir4ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("ELEGIR COLORES SECUNDARIOS A CAMBIAR");

        jbElegir5.setBackground(new java.awt.Color(255, 255, 255));
        jbElegir5.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jbElegir5.setText("+");
        jbElegir5.setBorderPainted(false);
        jbElegir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbElegir5ActionPerformed(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("RGB");

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("HEX");

        javax.swing.GroupLayout jpRespuesta5Layout = new javax.swing.GroupLayout(jpRespuesta5);
        jpRespuesta5.setLayout(jpRespuesta5Layout);
        jpRespuesta5Layout.setHorizontalGroup(
            jpRespuesta5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpRespuesta5Layout.setVerticalGroup(
            jpRespuesta5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        ACTUALIZAR.setBackground(new java.awt.Color(255, 255, 153));
        ACTUALIZAR.setText("MODIFICAR");
        ACTUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACTUALIZARActionPerformed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app2/Peq1.png"))); // NOI18N

        jbVolverInsertar1.setBackground(new java.awt.Color(255, 255, 255));
        jbVolverInsertar1.setText("VOLVER");
        jbVolverInsertar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverInsertar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpActualizarLayout = new javax.swing.GroupLayout(jpActualizar);
        jpActualizar.setLayout(jpActualizarLayout);
        jpActualizarLayout.setHorizontalGroup(
            jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpActualizarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpActualizarLayout.createSequentialGroup()
                        .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpActualizarLayout.createSequentialGroup()
                                .addComponent(jpRespuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlHex3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbElegir3)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jlRGB3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19)
                    .addGroup(jpActualizarLayout.createSequentialGroup()
                        .addComponent(jpRespuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlHex4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlRGB4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbElegir4))
                    .addGroup(jpActualizarLayout.createSequentialGroup()
                        .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbVolverInsertar1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jpRespuesta5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpActualizarLayout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlHex5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlRGB5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbElegir5))
                            .addComponent(ACTUALIZAR))))
                .addGap(115, 115, 115))
        );
        jpActualizarLayout.setVerticalGroup(
            jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpActualizarLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbElegir3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpRespuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlRGB3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlHex3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpRespuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlHex4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpActualizarLayout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlRGB4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jbElegir4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpRespuesta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlHex5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpActualizarLayout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlRGB5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jbElegir5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89)
                .addGroup(jpActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACTUALIZAR)
                    .addComponent(jbVolverInsertar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel23))
        );

        jpEliminar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("HEX");

        jbElegir6.setBackground(new java.awt.Color(255, 255, 255));
        jbElegir6.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jbElegir6.setText("-");
        jbElegir6.setBorderPainted(false);
        jbElegir6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbElegir6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpRespuesta6Layout = new javax.swing.GroupLayout(jpRespuesta6);
        jpRespuesta6.setLayout(jpRespuesta6Layout);
        jpRespuesta6Layout.setHorizontalGroup(
            jpRespuesta6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        jpRespuesta6Layout.setVerticalGroup(
            jpRespuesta6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("RGB");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("ELEGIR COLOR PRINCIPAL A ELIMINAR");

        ELIMINAR.setBackground(new java.awt.Color(255, 153, 153));
        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARActionPerformed(evt);
            }
        });

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app2/Peq1.png"))); // NOI18N

        jbVolverInsertar2.setBackground(new java.awt.Color(255, 255, 255));
        jbVolverInsertar2.setText("VOLVER");
        jbVolverInsertar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverInsertar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpEliminarLayout = new javax.swing.GroupLayout(jpEliminar);
        jpEliminar.setLayout(jpEliminarLayout);
        jpEliminarLayout.setHorizontalGroup(
            jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEliminarLayout.createSequentialGroup()
                        .addComponent(jbVolverInsertar2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214)
                        .addComponent(ELIMINAR))
                    .addGroup(jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpEliminarLayout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbElegir6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpEliminarLayout.createSequentialGroup()
                            .addComponent(jpRespuesta6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlHex6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jlRGB6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(117, 117, 117))
        );
        jpEliminarLayout.setVerticalGroup(
            jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEliminarLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbElegir6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpRespuesta6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlRGB6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlHex6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(286, 286, 286)
                .addGroup(jpEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ELIMINAR)
                    .addComponent(jbVolverInsertar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel31))
        );

        jpConsultar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("MI PALETA DE COLORES");

        CONSULTAR.setBackground(new java.awt.Color(153, 204, 255));
        CONSULTAR.setText("CONSULTAR");
        CONSULTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSULTARActionPerformed(evt);
            }
        });

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app2/Peq1.png"))); // NOI18N

        jbVolverInsertar3.setBackground(new java.awt.Color(255, 255, 255));
        jbVolverInsertar3.setText("VOLVER");
        jbVolverInsertar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverInsertar3ActionPerformed(evt);
            }
        });

        jtaRESPUESTA.setColumns(20);
        jtaRESPUESTA.setRows(5);
        jScrollPane1.setViewportView(jtaRESPUESTA);

        javax.swing.GroupLayout jpConsultarLayout = new javax.swing.GroupLayout(jpConsultar);
        jpConsultar.setLayout(jpConsultarLayout);
        jpConsultarLayout.setHorizontalGroup(
            jpConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jpConsultarLayout.createSequentialGroup()
                        .addComponent(jbVolverInsertar3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214)
                        .addComponent(CONSULTAR))
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpConsultarLayout.setVerticalGroup(
            jpConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultarLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CONSULTAR)
                    .addComponent(jbVolverInsertar3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMiPaleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMiPaleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbElegirActionPerformed
        // TODO add your handling code here:
        JColorChooser ColorChooser = new JColorChooser();
        Color newColor = JColorChooser.showDialog(null, " ", Color.WHITE);
        
         jpRespuesta.setBackground(newColor); // aplicar color a fondo panel
         
         //Sacamos colores por RGB
         int cred = newColor.getRed();
         int cgreen = newColor.getGreen();
         int cblue = newColor.getBlue();
      
         //sacamos valor HEX
         this.hex = Integer.toHexString(newColor.getRGB() & 0xffffff);
                                //hex= hex.substring(2,hex.length());

         //pasamos valores a interfase RGB
         this.cod = String.valueOf(cred)+" "+String.valueOf(cgreen)+" "+String.valueOf(cblue);
         jlRGB.setText(cod);
         //pasamos valores a base RGB
         
         //pasamos valor HEX a interface
         hex="#"+hex;
         jlHex.setText(hex);
         //pasamos valor HEX a base
         
         
    }//GEN-LAST:event_jbElegirActionPerformed

    private void jbInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInsertarActionPerformed
        // TODO add your handling code here:
        jpInsertar.setVisible(true);
        jpMiPaleta.setVisible(false);
        jpActualizar.setVisible(false);
        jpEliminar.setVisible(false);
        jpConsultar.setVisible(false);
    }//GEN-LAST:event_jbInsertarActionPerformed

    private void jbElegir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbElegir1ActionPerformed
        // TODO add your handling code here:
        JColorChooser ColorChooser = new JColorChooser();
        Color newColor = JColorChooser.showDialog(null, " ", Color.WHITE);
        
         jpRespuesta1.setBackground(newColor); // aplicar color a fondo panel
         
         //Sacamos colores por RGB
         int cred1 = newColor.getRed();
         int cgreen1 = newColor.getGreen();
         int cblue1 = newColor.getBlue();
      
         //sacamos valor HEX
         this.hex1 = Integer.toHexString(newColor.getRGB() & 0xffffff);
                                //hex= hex.substring(2,hex.length());
                                
         //pasamos valores a interfase RGB
         this.cod1 = String.valueOf(cred1)+" "+String.valueOf(cgreen1)+" "+String.valueOf(cblue1);
         jlRGB1.setText(cod1);
         //pasamos valores a base RGB
         
         //pasamos valor HEX a interface
         hex1="#"+hex1;
         jlHex1.setText(hex1);
         //pasamos valor HEX a base
    }//GEN-LAST:event_jbElegir1ActionPerformed

    private void jbElegir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbElegir2ActionPerformed
        // TODO add your handling code here:
        JColorChooser ColorChooser = new JColorChooser();
        
        
        Color newColor = JColorChooser.showDialog(null, " ", Color.WHITE);
        
         jpRespuesta2.setBackground(newColor); // aplicar color a fondo panel
         
         //Sacamos colores por RGB
         int cred2 = newColor.getRed();
         int cgreen2 = newColor.getGreen();
         int cblue2 = newColor.getBlue();
      
         //sacamos valor HEX
         this.hex2 = Integer.toHexString(newColor.getRGB() & 0xffffff);
                                //hex= hex.substring(2,hex.length());
                                
         //pasamos valores a interfase RGB
         this.cod2 = String.valueOf(cred2)+" "+String.valueOf(cgreen2)+" "+String.valueOf(cblue2);
         jlRGB2.setText(cod2);
         //pasamos valores a base RGB
         
         //pasamos valor HEX a interface
         hex2="#"+hex2;
         jlHex2.setText(hex2);
         //pasamos valor HEX a base
    }//GEN-LAST:event_jbElegir2ActionPerformed

    public static void conexion(){
    
        Connection conexion = null;
        String cadenaConexion="jdbc:mysql://localhost:3306/colores";
        //user-color   Segur1d@D
        //GRANT ALL PRIVILEGES ON colores.* TO 'user-color'@localhost IDENTIFIED BY 'Segur1d@D';
 
        try(Connection con = (Connection) DriverManager.getConnection(cadenaConexion, "user-colores","Segur1d@D");
            Statement sent= con.createStatement();){
            System.out.println("HAY CONECCION");
           }catch(SQLException e) {
            System.out.println("NO HAY CONECCION");
        }
        
    }
    
    public void CreateTable(){
        //conectamos al base creada previamente y creamos la tabla
        Connection conexion = null;
        //ruta de la base
        String cadenaConexion="jdbc:mysql://localhost:3306/colores";
         //user-color   Segur1d@D
        //GRANT ALL PRIVILEGES ON colores.* TO 'user-color'@localhost IDENTIFIED BY 'Segur1d@D';
        try(Connection con = (Connection) DriverManager.getConnection(cadenaConexion,"user-colores","Segur1d@D");
            Statement sent= con.createStatement();){
            
          int resultado;  
         
           resultado = sent.executeUpdate("CREATE TABLE micolores (\n" +
"                           cod_principal varchar(25) PRIMARY KEY,\n" +
"                           rgb_principal varchar(25),\n" +
"                           cod_sec1 varchar(25),\n" +
"                           rgb_sec1 varchar(25),\n" +
"                           cod_sec2 varchar(25),\n" +
"                           rgb_sec2 varchar(25));");
           
           //Mensaje interno
            System.out.println("La TABLA CREADA");
    
      }catch(SQLException e) {
            e.printStackTrace();
            //Mensaje interno
            System.out.println("NO SE PUEDE CREAR LA TABLA");
        }
    }
    
    private void INSERTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSERTARActionPerformed
        //Revisamos si tabla existe
       // CreateTable();
        
        //Insertamos datos 
        Connection conexion = null;
        String cadenaConexion="jdbc:mysql://localhost:3306/colores";
        try(Connection con = (Connection) DriverManager.getConnection(cadenaConexion,"user-colores","Segur1d@D");
            Statement sent= con.createStatement();){
            try{
          int resultado;  
            resultado = sent.executeUpdate("INSERT INTO micolores VALUES('"+this.cod+"', '"+this.hex+"', '"+this.cod1+"', '"+this.hex1+"', '"+this.cod2+"', '"+this.hex2+"');\n");
            System.out.println("INSERTADO");
            }catch(SQLException sqle){
              sqle.printStackTrace();
                System.out.println("ERROR, DATOS NO INSERTADOS");
            }

         //  conexion.close();
           }catch(SQLException e) {
            e.printStackTrace();
            System.out.println("ERROR DE CONECCION");
        }
    }//GEN-LAST:event_INSERTARActionPerformed

    private void jbVolverInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverInsertarActionPerformed
        // TODO add your handling code here:
        jpMiPaleta.setVisible(true);
        jpInsertar.setVisible(false);
        jpActualizar.setVisible(false);
        jpEliminar.setVisible(false);
        jpConsultar.setVisible(false);
    }//GEN-LAST:event_jbVolverInsertarActionPerformed

    private void jbVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverMenuActionPerformed
        // TODO add your handling code here:
        PaletaColores pc = new PaletaColores();
        pc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbVolverMenuActionPerformed

    private void jbElegir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbElegir3ActionPerformed
        JColorChooser ColorChooser = new JColorChooser();
        
        
        Color newColor = JColorChooser.showDialog(null, " ", Color.WHITE);
        
         jpRespuesta3.setBackground(newColor); // aplicar color a fondo panel
         
         //Sacamos colores por RGB
         int cred3 = newColor.getRed();
         int cgreen3 = newColor.getGreen();
         int cblue3 = newColor.getBlue();
      
         //sacamos valor HEX
         this.hex3 = Integer.toHexString(newColor.getRGB() & 0xffffff);
                                //hex= hex.substring(2,hex.length());
                                
         //pasamos valores a interfase RGB
         this.cod3 = String.valueOf(cred3)+" "+String.valueOf(cgreen3)+" "+String.valueOf(cblue3);
         jlRGB3.setText(cod3);
         //pasamos valores a base RGB
         
         //pasamos valor HEX a interface
         hex3="#"+hex3;
         jlHex3.setText(hex3);
         //pasamos valor HEX a base  
    }//GEN-LAST:event_jbElegir3ActionPerformed

    private void jbElegir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbElegir4ActionPerformed
        JColorChooser ColorChooser = new JColorChooser();
        
        
        Color newColor = JColorChooser.showDialog(null, " ", Color.WHITE);
        
         jpRespuesta4.setBackground(newColor); // aplicar color a fondo panel
         
         //Sacamos colores por RGB
         int cred4 = newColor.getRed();
         int cgreen4 = newColor.getGreen();
         int cblue4 = newColor.getBlue();
      
         //sacamos valor HEX
         this.hex4 = Integer.toHexString(newColor.getRGB() & 0xffffff);
                                //hex= hex.substring(2,hex.length());
                                
         //pasamos valores a interfase RGB
         this.cod4 = String.valueOf(cred4)+" "+String.valueOf(cgreen4)+" "+String.valueOf(cblue4);
         jlRGB4.setText(cod4);
         //pasamos valores a base RGB
         
         //pasamos valor HEX a interface
         hex4="#"+hex4;
         jlHex4.setText(hex4);
         //pasamos valor HEX a base
    }//GEN-LAST:event_jbElegir4ActionPerformed

    private void jbElegir5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbElegir5ActionPerformed
        JColorChooser ColorChooser = new JColorChooser();
        
        
        Color newColor = JColorChooser.showDialog(null, " ", Color.WHITE);
        
         jpRespuesta5.setBackground(newColor); // aplicar color a fondo panel
         
         //Sacamos colores por RGB
         int cred5 = newColor.getRed();
         int cgreen5 = newColor.getGreen();
         int cblue5 = newColor.getBlue();
      
         //sacamos valor HEX
         this.hex5 = Integer.toHexString(newColor.getRGB() & 0xffffff);
                                //hex= hex.substring(2,hex.length());
                                
         //pasamos valores a interfase RGB
         this.cod5 = String.valueOf(cred5)+" "+String.valueOf(cgreen5)+" "+String.valueOf(cblue5);
         jlRGB5.setText(cod5);
         //pasamos valores a base RGB
         
         //pasamos valor HEX a interface
         hex5="#"+hex5;
         jlHex5.setText(hex5);
         //pasamos valor HEX a base
    }//GEN-LAST:event_jbElegir5ActionPerformed

    private void ACTUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACTUALIZARActionPerformed
        //Revisamos si tabla existe
       // CreateTable();
        
        //Modificamos datos 
        Connection conexion = null;
        String cadenaConexion="jdbc:mysql://localhost:3306/colores";
        try(Connection con = (Connection) DriverManager.getConnection(cadenaConexion,"user-colores","Segur1d@D");
            Statement sent= con.createStatement();){
            try{
          int resultado;  
            resultado = sent.executeUpdate("UPDATE micolores SET cod_principal='"+this.cod3+"', rgb_principal='"+this.hex3+"', cod_sec1='"+this.cod4+"', rgb_sec1='"+this.hex4+"', cod_sec2='"+this.cod5+"', rgb_sec2='"+this.hex5+"' WHERE cod_principal='"+this.cod3+"';\n");
            System.out.println("MODIFICADO");
            }catch(SQLException sqle){
              sqle.printStackTrace();
                System.out.println("ERROR, DATOS NO MODIFICADOS");
            }

         //  conexion.close();
           }catch(SQLException e) {
            e.printStackTrace();
            System.out.println("ERROR DE CONECCION");
        }
 
        
    }//GEN-LAST:event_ACTUALIZARActionPerformed

    private void jbVolverInsertar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverInsertar1ActionPerformed
        // TODO add your handling code here:
        jpMiPaleta.setVisible(true);
        jpActualizar.setVisible(false);
        jpInsertar.setVisible(false);
        jpEliminar.setVisible(false);
        jpConsultar.setVisible(false);
    }//GEN-LAST:event_jbVolverInsertar1ActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        jpMiPaleta.setVisible(false);
        jpActualizar.setVisible(true);
        jpInsertar.setVisible(false);
        jpEliminar.setVisible(false);
        jpConsultar.setVisible(false);
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbElegir6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbElegir6ActionPerformed
        JColorChooser ColorChooser = new JColorChooser();

        Color newColor = JColorChooser.showDialog(null, " ", Color.WHITE);
        
         jpRespuesta6.setBackground(newColor); // aplicar color a fondo panel
         
         //Sacamos colores por RGB
         int cred6 = newColor.getRed();
         int cgreen6 = newColor.getGreen();
         int cblue6 = newColor.getBlue();
      
         //sacamos valor HEX
         this.hex6 = Integer.toHexString(newColor.getRGB() & 0xffffff);
                                //hex= hex.substring(2,hex.length());
                                
         //pasamos valores a interfase RGB
         this.cod6 = String.valueOf(cred6)+" "+String.valueOf(cgreen6)+" "+String.valueOf(cblue6);
         jlRGB6.setText(cod6);
         //pasamos valores a base RGB
         
         //pasamos valor HEX a interface
         hex6="#"+hex6;
         jlHex6.setText(hex6);
         //pasamos valor HEX a base
        
        
        
        
        
        
    }//GEN-LAST:event_jbElegir6ActionPerformed

    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARActionPerformed
        //Revisamos si tabla existe
       // CreateTable();
        
        //Eliminamos datos 
        Connection conexion = null;
        String cadenaConexion="jdbc:mysql://localhost:3306/colores";
        try(Connection con = (Connection) DriverManager.getConnection(cadenaConexion,"user-colores","Segur1d@D");
            Statement sent= con.createStatement();){
            try{
          int resultado;  
            resultado = sent.executeUpdate("DELETE FROM micolores WHERE cod_principal='"+this.cod6+"';");
            System.out.println("ELIMINADO");
            }catch(SQLException sqle){
              sqle.printStackTrace();
                System.out.println("ERROR, DATOS NO ELIMINADOS");
            }

         //  conexion.close();
           }catch(SQLException e) {
            e.printStackTrace();
            System.out.println("ERROR DE CONECCION");
        }
        
    }//GEN-LAST:event_ELIMINARActionPerformed

    private void jbVolverInsertar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverInsertar2ActionPerformed
        // TODO add your handling code here:
        jpMiPaleta.setVisible(true);
        jpEliminar.setVisible(false);
        jpInsertar.setVisible(false);
        jpActualizar.setVisible(false);
        jpConsultar.setVisible(false);
    }//GEN-LAST:event_jbVolverInsertar2ActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        jpMiPaleta.setVisible(false);
        jpEliminar.setVisible(true);
        jpInsertar.setVisible(false);
        jpActualizar.setVisible(false);
        jpConsultar.setVisible(false);
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void CONSULTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSULTARActionPerformed
         //Revisamos si tabla existe
     //   CreateTable();
        
        //Consultamos
        Connection conexion = null;
        String cadenaConexion="jdbc:mysql://localhost:3306/colores";
        try(Connection con = (Connection) DriverManager.getConnection(cadenaConexion,"user-colores","Segur1d@D");
            Statement sent= con.createStatement();
            ResultSet rs=sent.executeQuery("SELECT * FROM micolores;");){      
            int i=1;
            jtaRESPUESTA.setText(" "+"\n");
             while(rs.next()){
                String cod = rs.getString("cod_principal");
                String hex = rs.getString("rgb_principal");
                String cod1 = rs.getString("cod_sec1");
                String hex1 = rs.getString("rgb_sec1");
                String cod2 = rs.getString("cod_sec2");
                String hex2 = rs.getString("rgb_sec2");
                
                System.out.println(rs.getString("cod_principal"));
                System.out.println(rs.getString("rgb_principal"));
                System.out.println(rs.getString("cod_sec1"));
                System.out.println(rs.getString("rgb_sec1"));
                System.out.println(rs.getString("cod_sec2"));
                System.out.println(rs.getString("rgb_sec2"));
                
                jtaRESPUESTA.append(i+" - "+cod + " - "+hex+" -------"+cod1+" - "+hex1+" --- "+cod2+" - "+hex2+"\n");
                i++;
            }  
         //  conexion.close();
        }catch(SQLException e) {
            e.printStackTrace();
            System.out.println("ERROR DE CONSULTA");
        }    
    }//GEN-LAST:event_CONSULTARActionPerformed

    private void jbVolverInsertar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverInsertar3ActionPerformed
        // TODO add your handling code here:
        jpMiPaleta.setVisible(true);
        jpConsultar.setVisible(false);
        jpInsertar.setVisible(false);
        jpActualizar.setVisible(false);
        jpEliminar.setVisible(false);
    }//GEN-LAST:event_jbVolverInsertar3ActionPerformed

    private void jbConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarActionPerformed
        // TODO add your handling code here:
        jpMiPaleta.setVisible(false);
        jpConsultar.setVisible(true);
        jpInsertar.setVisible(false);
        jpActualizar.setVisible(false);
        jpEliminar.setVisible(false);
        
    }//GEN-LAST:event_jbConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiColores().setVisible(true);
                conexion();
                
            }
        });
    }
public MiColores() {
        initComponents();
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACTUALIZAR;
    private javax.swing.JButton CONSULTAR;
    private javax.swing.JButton ELIMINAR;
    private javax.swing.JButton INSERTAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JButton jbElegir;
    private javax.swing.JButton jbElegir1;
    private javax.swing.JButton jbElegir2;
    private javax.swing.JButton jbElegir3;
    private javax.swing.JButton jbElegir4;
    private javax.swing.JButton jbElegir5;
    private javax.swing.JButton jbElegir6;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbInsertar;
    private javax.swing.JButton jbVolverInsertar;
    private javax.swing.JButton jbVolverInsertar1;
    private javax.swing.JButton jbVolverInsertar2;
    private javax.swing.JButton jbVolverInsertar3;
    private javax.swing.JButton jbVolverMenu;
    private javax.swing.JLabel jlHex;
    private javax.swing.JLabel jlHex1;
    private javax.swing.JLabel jlHex2;
    private javax.swing.JLabel jlHex3;
    private javax.swing.JLabel jlHex4;
    private javax.swing.JLabel jlHex5;
    private javax.swing.JLabel jlHex6;
    private javax.swing.JLabel jlRGB;
    private javax.swing.JLabel jlRGB1;
    private javax.swing.JLabel jlRGB2;
    private javax.swing.JLabel jlRGB3;
    private javax.swing.JLabel jlRGB4;
    private javax.swing.JLabel jlRGB5;
    private javax.swing.JLabel jlRGB6;
    private javax.swing.JPanel jpActualizar;
    private javax.swing.JPanel jpConsultar;
    private javax.swing.JPanel jpEliminar;
    private javax.swing.JPanel jpInsertar;
    private javax.swing.JPanel jpMiPaleta;
    private javax.swing.JPanel jpRespuesta;
    private javax.swing.JPanel jpRespuesta1;
    private javax.swing.JPanel jpRespuesta2;
    private javax.swing.JPanel jpRespuesta3;
    private javax.swing.JPanel jpRespuesta4;
    private javax.swing.JPanel jpRespuesta5;
    private javax.swing.JPanel jpRespuesta6;
    private javax.swing.JTextArea jtaRESPUESTA;
    // End of variables declaration//GEN-END:variables
}
